# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DealPhoto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DealPhoto
pod 'OpenCV2', '~> 4.3.0'
pod 'SnapKit'
pod 'R.swift'
pod 'MJRefresh'
pod 'SwifterSwift'
pod 'SwiftyStoreKit'
pod 'HBDNavigationBar'
pod 'ReachabilitySwift'
pod 'SwiftyUserDefaults'
pod 'SwiftMessages'

end
